### ISSUE TITLE
Add Worker Nodes into AKS 

### ISSUE THREAD

**Issue by ciscosom** [Azure/iot-edge-virtual-kubelet-provider#12]
Greetings , 

Can we manage  the hardware gateways or external servers (outside of Azure) running docker as "worker nodes" on  Azure Kubernetes services  . I know this is possible on  IOT HUB -> Edge blade . Can you please clarify .

**Comment by veyalla** [comment]
@ciscosom It is not possible via this project. You'd have to create your own custom provider for virtual-kubelet I think.
