### ISSUE TITLE
VK IoT Edge Provider does not support IoT Edge GA

### ISSUE THREAD

**Issue by neumanndaniel** [Azure/iot-edge-virtual-kubelet-provider#18]
Just raising another issue. As far as I have experienced today the VK IoT Edge Provider is not compatible anymore with IoT Edge in its GA version.

Running a deployment always references to the old images microsoft/azureiotedge-agent:1.0-preview instead of the new ones mcr.microsoft.com/azureiotedge-agent:1.0 which causes the whole deployment to fail. Even with the a ConfigMap I am unable to override the settings for the edgeAgent for the images and especially for the container registry ACR. E.g.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgeagent
data:
  desiredProperties: |
    {
      "schemaVersion": "1.0",
      "runtime": {
        "settings": {
          "registryCredentials": {
            "acr": {
              "address": "REDACTED",
              "password": "REDACTED",
              "username": "REDACTED"
            }
          }
        }
      },
      "systemModules": {
        "edgeAgent": {
          "settings": {
            "image": "mcr.microsoft.com/azureiotedge-agent:1.0"
          }
        },
        "edgeHub": {
          "settings": {
            "image": "mcr.microsoft.com/azureiotedge-hub:1.0"
          }
        }
      },
    }
```

**Comment by veyalla** [comment]
#19 fixes this.
