### ISSUE TITLE
Adding container image as environment variable

### ISSUE THREAD

**Issue by neumanndaniel** [Azure/iot-edge-virtual-kubelet-provider#20]
We released yesterday version 1.0.1 of the Azure IoT Edge (https://azure.microsoft.com/en-us/updates/iot-edge1-0-1/). So, we should implement the container image reference for EdgeAgent and EdgeHub as environment variable as stated in this PR.

-> https://github.com/Azure/iot-edge-virtual-kubelet-provider/pull/19#discussion_r199002782

Will try to implement this in the next couple of days. FYI @avranju @veyalla

**Comment by veyalla** [comment]
Tag 1.0 is actually an alias of 1.0.1. 

So any new deployments will pull down the 1.0.1 even when using the  1.0 tag.

**Comment by neumanndaniel** [comment]
Should we keep the issue open or just close it and re-open, when e.g. releasing version 2.0?

**Comment by veyalla** [comment]
I guess we can close it for now, and re-open when nearing 2.0 release.

**Comment by neumanndaniel** [comment]
Will re-open and fix, when nearing 2.0 release.
