### ISSUE TITLE
New microsoft/iot-edge-vk-provider image needs to be build

### ISSUE THREAD

**Issue by neumanndaniel** [Azure/iot-edge-virtual-kubelet-provider#30]
For users that use the default values in the Helm chart and do not build their own container image, the default image at microsoft/iot-edge-vk-provider needs to be updated. 

The last build is one year old.

-> https://hub.docker.com/r/microsoft/iot-edge-vk-provider/tags

/cc @veyalla

**Comment by veyalla** [comment]
This has (finally) been updated. The `latest` tag should be up-to-date with master.
