### ISSUE TITLE
namespace hub0 does not exist

### ISSUE THREAD

**Issue by mariojacobo** [Azure/iot-edge-virtual-kubelet-provider#36]
the command ```helm install -n hub0 src/charts/iot-edge-connector``` tries to install the chart in the namespace hub0, however this was not created/declared anywhere.  it makes sense to use the default namespace, since that's where we gave cluster-admin permission (or tried to, since the command below seems wrong to me)

Also, ```kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default```, grants cluster-admin role to the default service account in the kube-system namespace, not the default namespace., like the doc says 

Am I missing something here ?

**Comment by veyalla** [comment]
Updated the readme for Helm 3, which should fix this. Please follow the updated instructions.
