### ISSUE TITLE
Make this instruction more clear

### ISSUE THREAD

**Issue by rbitia** [Azure/iot-edge-virtual-kubelet-provider#5]
kubectl create secret generic my-secrets \
 --from-literal=hub0-cs='<iot-hub-owner-connection-string>'

Once I figure out how to find the iot-hub-owner string I'll be able to create PR a fix. but I can't figure out how to find the string in the portal

**Comment by veyalla** [comment]
Thanks for pointing out. I will add some links in the quickstart to get started with IoT Hub and IoT Edge.
